//checking
export const UP_COUNTER_STATUS = 'UP_COUNTER_STATUS';
export const TOGGLE_CHECKING_OPEN = 'TOGGLE_CHECKING_OPEN';

//input
export const CHANGE_INPUT = 'CHANGE_INPUT';

//result
export const ADD_RESULT = 'ADD_RESULT';
export const TOGGLE_ANON = 'TOGGLE_ANON';
export const TOGGLE_PROTOCOL = 'TOGGLE_PROTOCOL';
export const TOGGLE_COUNTRY = 'TOGGLE_COUNTRY';
export const TOGGLE_EXTRA = 'TOGGLE_EXTRA';
export const SET_SEARCH = 'SET_SEARCH';
export const LOAD_MORE = 'LOAD_MORE';
export const RESULT_CLOSE = 'RESULT_CLOSE';
export const TOGGLE_OPEN = 'TOGGLE_OPEN';

//settings
export const CHANGE_SETTINGS = 'CHANGE_SETTINGS';
export const CHANGE_SETTINGS_JUDGE = 'CHANGE_SETTINGS_JUDGE';
export const ADD_SETTINGS_JUDGE = 'ADD_SETTINGS_JUDGE';
export const REMOVE_SETTINGS_JUDGE = 'REMOVE_SETTINGS_JUDGE';

//update
export const CHANGE_UPDATE_STATE = 'CHANGE_UPDATE_STATE';
export const UPDATE_UP_DOWNLOAD_PROGRESS = 'UPDATE_UP_DOWNLOAD_PROGRESS';
export const UPDATE_CLOSE = 'UPDATE_CLOSE';

//overlay ip
export const OVERLAY_IP_CHANGE_LOOKUP_STATUS = 'OVERLAY_IP_CHANGE_LOOKUP_STATUS';
export const OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL = 'OVERLAY_IP_CHANGE_LOOKUP_TO_INITIAL';

//overlay judges
export const OVERLAY_JUDGES_CHANGE_STATE = 'OVERLAY_JUDGES_CHANGE_STATE';
export const OVERLAY_JUDGE_CHANGE_PING_STATE = 'OVERLAY_JUDGE_CHANGE_PING_STATE';